-- Shared bone definitions
BoneList = {
    { label = "Root",               bone = "SKEL_ROOT",                  index = 0     },
    { label = "Pelvis",             bone = "SKEL_Pelvis",                index = 11816 },
    { label = "Spine Root",         bone = "SKEL_Spine_Root",            index = 57597 },
    { label = "Spine 0",            bone = "SKEL_Spine0",                index = 23553 },
    { label = "Spine 1",            bone = "SKEL_Spine1",                index = 24816 },
    { label = "Spine 2",            bone = "SKEL_Spine2",                index = 24817 },
    { label = "Spine 3",            bone = "SKEL_Spine3",                index = 24818 },
    { label = "Neck",               bone = "SKEL_Neck_1",                index = 39317 },
    { label = "Head",               bone = "SKEL_Head",                  index = 31086 },
    { label = "Left Clavicle",      bone = "SKEL_L_Clavicle",            index = 64729 },
    { label = "Left Upper Arm",     bone = "SKEL_L_UpperArm",            index = 45509 },
    { label = "Left Forearm",       bone = "SKEL_L_Forearm",             index = 61163 },
    { label = "Left Hand",          bone = "SKEL_L_Hand",                index = 18905 },
    { label = "Left Finger 0",      bone = "SKEL_L_Finger00",            index = 26610 },
    { label = "Left Finger 1",      bone = "SKEL_L_Finger10",            index = 4089  },
    { label = "Left Finger 2",      bone = "SKEL_L_Finger20",            index = 4090  },
    { label = "Left Finger 3",      bone = "SKEL_L_Finger30",            index = 4091  },
    { label = "Left Finger 4",      bone = "SKEL_L_Finger40",            index = 4092  },
    { label = "Right Clavicle",     bone = "SKEL_R_Clavicle",            index = 10706 },
    { label = "Right Upper Arm",    bone = "SKEL_R_UpperArm",            index = 40269 },
    { label = "Right Forearm",      bone = "SKEL_R_Forearm",             index = 43810 },
    { label = "Right Hand",         bone = "SKEL_R_Hand",                index = 57005 },
    { label = "Right Finger 0",     bone = "SKEL_R_Finger00",            index = 58866 },
    { label = "Right Finger 1",     bone = "SKEL_R_Finger10",            index = 64016 },
    { label = "Right Finger 2",     bone = "SKEL_R_Finger20",            index = 64017 },
    { label = "Right Finger 3",     bone = "SKEL_R_Finger30",            index = 64018 },
    { label = "Right Finger 4",     bone = "SKEL_R_Finger40",            index = 64019 },
    { label = "Left Hip",           bone = "SKEL_L_Thigh",               index = 58271 },
    { label = "Left Knee",          bone = "SKEL_L_Calf",                index = 63931 },
    { label = "Left Foot",          bone = "SKEL_L_Foot",                index = 14201 },
    { label = "Left Toe",           bone = "SKEL_L_Toe0",                index = 2108  },
    { label = "Right Hip",          bone = "SKEL_R_Thigh",               index = 51826 },
    { label = "Right Knee",         bone = "SKEL_R_Calf",                index = 36864 },
    { label = "Right Foot",         bone = "SKEL_R_Foot",                index = 52301 },
    { label = "Right Toe",          bone = "SKEL_R_Toe0",                index = 20781 },
    -- Extra ped bones
    { label = "Weapon R",           bone = "IK_R_Hand",                  index = 36029 },
    { label = "Weapon L",           bone = "IK_L_Hand",                  index = 65245 },
    { label = "Back (Spine 3)",     bone = "SKEL_Spine3",                index = 24818 },
    { label = "Chest R",            bone = "SKEL_R_UpperArm",            index = 40269 },
    { label = "Chest L",            bone = "SKEL_L_UpperArm",            index = 45509 },
}

-- Commonly used gun carry attachment presets
AttachmentPresets = {
    {
        label = "Back (Rifle)",
        bone  = 24818,
        offset = vec3(0.18, -0.08, -0.1),
        rotation = vec3(0.0, 0.0, 190.0),
    },
    {
        label = "Hip Holster (R)",
        bone  = 57005,
        offset = vec3(0.02, 0.02, -0.05),
        rotation = vec3(-180.0, 60.0, 0.0),
    },
    {
        label = "Chest Sling (L)",
        bone  = 45509,
        offset = vec3(-0.12, 0.06, -0.04),
        rotation = vec3(0.0, 90.0, 200.0),
    },
    {
        label = "Leg (Thigh R)",
        bone  = 51826,
        offset = vec3(0.08, 0.04, -0.12),
        rotation = vec3(0.0, 0.0, 90.0),
    },
}
